name: Build Angular App

on:
  push:
    branches: [main] # or staging, or any other branch you want
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Check Node.js version
      run: node -v
   

    - name: Install dependencies
      run: npm ci

    - name: Build Angular app
      run: npm run build

    - name: Copy build output to Nginx folder
      shell: powershell
      run: |
        New-Item -ItemType Directory -Path "C:\nginx\html" -Force
        Remove-Item -Recurse -Force "C:\nginx\html\*" -ErrorAction SilentlyContinue
        Copy-Item -Path "dist\*" -Destination "C:\nginx\html" -Recurse
